version: "3.8"

services:
  db:
    ports:
      - 5432:5432
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    extends:
      file: common.yml
      service: db

  pgadmin:
    ports:
      - 5000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    extends:
      file: common.yml
      service: pgadmin

  nginx:
    ports:
      - 80:80
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    extends:
      file: common.yml
      service: nginx

  backend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      HTTP_PORT: 3000
      DB_NAME: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ../backend/src:/app/src
    depends_on:
      - db
    extends:
      file: common.yml
      service: backend

  frontend:
    command: npm run dev
    ports:
      - 4000:4000
    volumes:
      - ../frontend/src:/app/src
      - /app/node_modules
    depends_on:
      - backend
    extends:
      file: common.yml
      service: frontend
