version: "3.8"

services:
  db:
    ports:
      - 5432:5432
    env_file:
      - path: ".env.dev"
        required: true
    volumes:
      - ./data-dev.sql:/docker-entrypoint-initdb.d/data.sql
    extends:
      file: common.yml
      service: db

  pgadmin:
    ports:
      - 5000:80
    env_file:
      - path: ".env.dev"
        required: true
    depends_on:
      - db
    extends:
      file: common.yml
      service: pgadmin

  nginx:
    ports:
      - 80:80
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    extends:
      file: common.yml
      service: nginx

  backend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - path: ".env.dev"
        required: true
    volumes:
      - ../backend/src:/app/src
    depends_on:
      - db
    extends:
      file: common.yml
      service: backend

  frontend:
    command: npm run dev
    ports:
      - 4000:4000
    env_file:
      - path: ".env.dev"
        required: true
    volumes:
      - ../frontend/src:/app/src
      - /app/node_modules
    depends_on:
      - backend
    extends:
      file: common.yml
      service: frontend
