services:
  db:
    ports:
      - 5432:5432
    env_file:
      - path: ".env.prod"
        required: true
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    extends:
      file: common.yml
      service: db

  nginx:
    ports:
      - 80:80
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    extends:
      file: common.yml
      service: nginx

  backend:
    build:
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file:
      - path: ".env.prod"
        required: true
    depends_on:
      - db
    extends:
      file: common.yml
      service: backend

  frontend:
    command: npm start
    ports:
      - 4000:4000
    env_file:
      - path: ".env.prod"
        required: true
    depends_on:
      - backend
    extends:
      file: common.yml
      service: frontend
