version: "3.8"

services:
  db:
    ports:
      - 5432:5432
    env_file:
      - path: ".env.test"
        required: true
    volumes:
      - ./data-test.sql:/docker-entrypoint-initdb.d/data.sql
    extends:
      file: common.yml
      service: db

  pgadmin:
    ports:
      - 5000:80
    env_file:
      - path: ".env.test"
        required: true
    depends_on:
      - db
    extends:
      file: common.yml
      service: pgadmin

  nginx:
    ports:
      - 80:80
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    extends:
      file: common.yml
      service: nginx

  backend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - path: ".env.test"
        required: true
    volumes:
      - ../backend/src:/app/src
      - ../backend/include:/app/include
    depends_on:
      - db
    extends:
      file: common.yml
      service: backend

  test:
    container_name: test
    build:
      context: ../backend
      dockerfile: Dockerfile.test
    ports:
      - 3333:3333
    env_file:
      - path: ".env.test"
        required: true
    volumes:
      - ../backend/test_setup/tests:/app/test_setup/tests
    depends_on:
      - db
      - backend
